os: linux
dist: bionic

services:
  - docker

language: java
jdk: openjdk11

# Copied from:
#   https://docs.travis-ci.com/user/languages/java/#caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install:
  - docker-compose up --detach
  - sleep 10  # Wait for dockers to boot up
  - docker-compose ps --all
  - ./gradlew assemble

script:
  - ./gradlew check --info
