name: build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '15'
      - run: |
          docker-compose up --detach
          sleep 10
          docker-compose ps
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: assemble
          gradle-version: current
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: check --info
          gradle-version: current
